// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: bibit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStockSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockCode string `protobuf:"bytes,1,opt,name=stockCode,proto3" json:"stockCode,omitempty"`
	Date      string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *GetStockSummaryRequest) Reset() {
	*x = GetStockSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bibit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockSummaryRequest) ProtoMessage() {}

func (x *GetStockSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bibit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetStockSummaryRequest) Descriptor() ([]byte, []int) {
	return file_bibit_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockSummaryRequest) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *GetStockSummaryRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetStockSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockCode string `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	Date      string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Prev      int64  `protobuf:"varint,3,opt,name=prev,proto3" json:"prev,omitempty"`
	Open      int64  `protobuf:"varint,4,opt,name=open,proto3" json:"open,omitempty"`
	High      int64  `protobuf:"varint,5,opt,name=high,proto3" json:"high,omitempty"`
	Low       int64  `protobuf:"varint,6,opt,name=low,proto3" json:"low,omitempty"`
	Close     int64  `protobuf:"varint,7,opt,name=close,proto3" json:"close,omitempty"`
	Volume    int64  `protobuf:"varint,8,opt,name=volume,proto3" json:"volume,omitempty"`
	Value     int64  `protobuf:"varint,9,opt,name=value,proto3" json:"value,omitempty"`
	Average   int64  `protobuf:"varint,10,opt,name=average,proto3" json:"average,omitempty"`
}

func (x *GetStockSummaryResponse) Reset() {
	*x = GetStockSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bibit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStockSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockSummaryResponse) ProtoMessage() {}

func (x *GetStockSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bibit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetStockSummaryResponse) Descriptor() ([]byte, []int) {
	return file_bibit_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockSummaryResponse) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *GetStockSummaryResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetStockSummaryResponse) GetPrev() int64 {
	if x != nil {
		return x.Prev
	}
	return 0
}

func (x *GetStockSummaryResponse) GetOpen() int64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *GetStockSummaryResponse) GetHigh() int64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *GetStockSummaryResponse) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *GetStockSummaryResponse) GetClose() int64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *GetStockSummaryResponse) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *GetStockSummaryResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetStockSummaryResponse) GetAverage() int64 {
	if x != nil {
		return x.Average
	}
	return 0
}

var File_bibit_proto protoreflect.FileDescriptor

var file_bibit_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x69, 0x62, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x22, 0xf8, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x72, 0x65, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70,
	0x72, 0x65, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6f, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x32, 0x59, 0x0a, 0x05, 0x42,
	0x69, 0x62, 0x69, 0x74, 0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bibit_proto_rawDescOnce sync.Once
	file_bibit_proto_rawDescData = file_bibit_proto_rawDesc
)

func file_bibit_proto_rawDescGZIP() []byte {
	file_bibit_proto_rawDescOnce.Do(func() {
		file_bibit_proto_rawDescData = protoimpl.X.CompressGZIP(file_bibit_proto_rawDescData)
	})
	return file_bibit_proto_rawDescData
}

var file_bibit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bibit_proto_goTypes = []interface{}{
	(*GetStockSummaryRequest)(nil),  // 0: proto.GetStockSummaryRequest
	(*GetStockSummaryResponse)(nil), // 1: proto.GetStockSummaryResponse
}
var file_bibit_proto_depIdxs = []int32{
	0, // 0: proto.Bibit.GetStockSummary:input_type -> proto.GetStockSummaryRequest
	1, // 1: proto.Bibit.GetStockSummary:output_type -> proto.GetStockSummaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bibit_proto_init() }
func file_bibit_proto_init() {
	if File_bibit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bibit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bibit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStockSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bibit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bibit_proto_goTypes,
		DependencyIndexes: file_bibit_proto_depIdxs,
		MessageInfos:      file_bibit_proto_msgTypes,
	}.Build()
	File_bibit_proto = out.File
	file_bibit_proto_rawDesc = nil
	file_bibit_proto_goTypes = nil
	file_bibit_proto_depIdxs = nil
}
